#########################################################################
# Title:         Cloudbox: Radarr4K Role                                #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/radarr                                           #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: radarr4k
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: radarr4k
    state: absent

- name: Remove darkerr config
  file:
    path: "/opt/nginx-proxy/vhost.d/radarr4k.{{ domain }}_location"
    state: absent
  when: not (darkerr.enable | default(false,true))

- name: Suitarr Migration Tasks
  import_tasks: "subtasks/suitarr_migration.yml"

- name: Create radarr4k directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user }} group={{ user }}"
  with_items:
    - /opt/radarr4k

- name: Add darkerr config
  copy:
    src: "darkerr-nginx-conf"
    dest: "/opt/nginx-proxy/vhost.d/radarr4k.{{ domain }}_location"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0664
    force: yes
  when: (darkerr.enable | default(false,true))

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/radarr4k:/config"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"
      - "/mnt/unionfs/Media/Movies:/movies"

- name: Create and start container
  docker_container:
    name: radarr4k
    image: "hotio/radarr"
    pull: yes
    published_ports:
      - "127.0.0.1:7879:7878"
    env:
      VERSION: "{{ suitarr.version }}"
      BACKUP: "no"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      UMASK: 002
      VIRTUAL_HOST: "radarr4k.{{domain}}"
      VIRTUAL_PORT: 7878
      LETSENCRYPT_HOST: "radarr4k.{{ domain }}"
      LETSENCRYPT_EMAIL: "{{ email }}"
      TZ: "{{ tz }}"
    volumes: "{{ default_volumes + nzbs_downloads_path|default([]) + torrents_downloads_path|default([]) }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - radarr4k
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
